######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 20 09:37:17 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

mac {
  CONFIG -= app_bundle
}

# Input
HEADERS += NetworkAccess.h
SOURCES += test.cpp
